### ISSUE TITLE
Error when running puppy-primers: "qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found."

### ISSUE THREAD

**Issue by cvtang** [Tropini-lab/PUPpy#9]
Because I am fairly new to bioinformatics and coding I wanted to share this in case anybody encountered this issue, because it took me some time to troubleshoot:

I got the following error when running puppy-primers command :

`puppy-primers -pr 1.Target -i ResultDB.tsv -o 1.Test1_Unique_primers`
 
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Aborted (core dumped)
```
After a bit of digging it seems like a common issue with the qt plugin, so I wanted to share the most useful forums and what worked for me:

 I started by following this [stacksoverflow answer](https://stackoverflow.com/questions/64695574/after-installing-pyqt5-5-14-0-error-shows-as-could-not-load-the-qt-platform-pl)

1) Determine issues with qt using the qt debugging set: 
`QT_DEBUG_PLUGINS=1 puppy-primers -pr 1.Target -i ResultDB.tsv -o 1.Test1_Unique_primers`

```
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/tools/miniconda3/envs/puppy1/bin/platforms" ...
Cannot load library /tools/miniconda3/envs/puppy1/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/tools/miniconda3/envs/puppy1/plugins/platforms/libqxcb.so" : "Cannot load library /tools/miniconda3/envs/puppy1/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Aborted (core dumped)
```

2) Identify the missing libraries: 
`ldd /tools/miniconda3/envs/puppy1/plugins/platforms/libqxcb.so | grep -i "not found"`
```

 libxcb-icccm.so.4 => not found
        libxcb-image.so.0 => not found
        libxcb-keysyms.so.1 => not found
        libxcb-render-util.so.0 => not found
```

3) Install the missing libraries
`sudo apt-get install libxcb-icccm.so.4 libxcb-image.so.0 libxcb-keysyms.so.1 libxcb-render-util.so.0`

I re ran the puppy-primers command, but got the same error- not sure if the issue was that I do not have sudo rights so I had to ask to get the programs installed.

Then[ I tried this which fixed the issue](https://github.com/NVlabs/instant-ngp/discussions/300)!
`export QT_QPA_PLATFORM=offscreen`

Hope this helps!

**Comment by hghezzi** [comment]
Thank you for sharing all your work!
